USE DATABASE RAW_DB_DEV;
USE SCHEMA STAGING;
CREATE OR REPLACE PIPE raw_patients_pipe
AUTO_INGEST = TRUE
AS
COPY INTO RAW_DB_DEV.STAGING.RAW_PATIENTS
FROM @disease_inv_stage
FILE_FORMAT = (FORMAT_NAME = csv_ff)
ON_ERROR = 'CONTINUE';



