USE DATABASE RAW_DB_DEV;
USE SCHEMA STAGING;
CREATE OR REPLACE PIPE raw_diseases_pipe
AUTO_INGEST = TRUE
AS
COPY INTO RAW_DB_DEV.STAGING.RAW_DISEASES_WITH_IDS
FROM @disease_inv_stage/disease_with_ids.csv
FILE_FORMAT = (FORMAT_NAME = csv_ff)
ON_ERROR = 'CONTINUE';
