name: 'Disease_trends_analysis_medicine_inventory_optimization'
version: '1.0.0'
config-version: 2

# Match your profile name in dbt Cloud / profiles.yml
profile: 'Disease_trends_analysis_medicine_inventory_optimization'

models:
  Disease_trends_analysis_medicine_inventory_optimization:

    # STAGING MODELS
    staging:
      +materialized: view
      +schema: STAGING       # RAW_DB_DEV.STAGING (from staging sources)

    # TRANSFORMED MODELS
    transformed:
      +database: TRANSFORMED_DB_DEV

      # Patients Domain
      patients:
        dim:
          +materialized: table
          +schema: PATIENTS   # => TRANSFORMED_DB_DEV.PATIENTS
        facts:
          +materialized: table
          +schema: PATIENTS   # => TRANSFORMED_DB_DEV.PATIENTS

      # Inventory Domain
      inventory:
        dim:
          +materialized: table
          +schema: INVENTORY  # => TRANSFORMED_DB_DEV.INVENTORY
        fact:
          +materialized: table
          +schema: INVENTORY  # => TRANSFORMED_DB_DEV.INVENTORY
