[connections.raw_connection]
account = { env = "SNOWFLAKE_ACCOUNT" }
user = { env = "SNOWFLAKE_USER" }
password = { env = "SNOWFLAKE_PASSWORD" }
role = { env = "SNOWFLAKE_ROLE" }
warehouse = { env = "SNOWFLAKE_WH" }
database = "RAW_DB_DEV"
schema = "SCHEMACHANGE"
